baseurl: ''
permalink: pretty
title: 'Apex Arcana'
email: 'webmaster@arcana.com.au'
description: 'Data and IT solutions for integration, scale and better human experiences. Leverage 25 years of experience to understand and solve your hardest problems.'

# url: "http://arcana.com.au" # the base hostname & protocol for your site, e.g. http://example.com

homepage:
  show_call_box: true

footer:
  copyright_text: 'Free Jekyll theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>'

seo:
  meta_og_title: "Apex Arcana - IT Consulting"
  meta_og_type: "website"
  meta_og_url: "https://arcana.com.au"
  meta_og_image: "https://arcana.com.au/images/social.png"
  meta_og_description: "Data and IT solutions for integration, scale and better human experiences. Leverage 25 years of experience to understand and solve your hardest problems."
  google_analytics_id: "G-DML1QM0XS9"

logo:
  mobile: "images/logo/logo.svg"
  desktop: "images/logo/logo.svg"
  desktop_height: "50px"

home: 
  limit_services: 4

collections:
  services:
    output: true
  team:
    output: false

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

url: "https://arcana.com.au"

plugins:
  - jekyll-environment-variables
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md

